FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY alembic.ini ./
COPY alembic ./alembic

ENV PYTHONPATH=/app

CMD celery -A app.core.celery:celery_app worker --loglevel=info -Q ai.chat,ai.vision,ai.resume,speech,translate,email,maintenance,licensing,celery
