export {
  ensureOverlayWindow,
  showOverlay,
  hideOverlay,
  toggleOverlay,
  getCompanionWindow,
  getCompanionBridgeStatus,
  getCompanionWindowState,
  showCompanion,
  hideCompanion,
  toggleCompanion,
  createCompanionWindow,
  setCompanionMode,
  setCompanionPinned,
  setCompanionOpacity,
  expandCompanion,
  restoreCompanion,
  resetCompanionSize,
  companionUserActivity,
  allowCompanionQuit,
  beginOverlayResize,
  endOverlayResize,
  isOverlayAvailable,
  destroyOverlay,
  type CompanionBridgeStatus,
  type CompanionWindowState,
  type ResizeDirection,
} from "../services/overlay-window-manager";
